// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person/person.proto

package personpb

import (
	eye "eye"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PersonMessage struct {
	Age                  int32         `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	FirstName            string        `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string        `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	EyeColour            eye.EyeColour `protobuf:"varint,4,opt,name=eye_colour,json=eyeColour,proto3,enum=example.eye.EyeColour" json:"eye_colour,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PersonMessage) Reset()         { *m = PersonMessage{} }
func (m *PersonMessage) String() string { return proto.CompactTextString(m) }
func (*PersonMessage) ProtoMessage()    {}
func (*PersonMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e25b6e050ad8ae9a, []int{0}
}

func (m *PersonMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonMessage.Unmarshal(m, b)
}
func (m *PersonMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonMessage.Marshal(b, m, deterministic)
}
func (m *PersonMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonMessage.Merge(m, src)
}
func (m *PersonMessage) XXX_Size() int {
	return xxx_messageInfo_PersonMessage.Size(m)
}
func (m *PersonMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PersonMessage proto.InternalMessageInfo

func (m *PersonMessage) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *PersonMessage) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *PersonMessage) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *PersonMessage) GetEyeColour() eye.EyeColour {
	if m != nil {
		return m.EyeColour
	}
	return eye.EyeColour_UNKNOWN_EYE_COLOUR
}

func init() {
	proto.RegisterType((*PersonMessage)(nil), "example.person.PersonMessage")
}

func init() { proto.RegisterFile("person/person.proto", fileDescriptor_e25b6e050ad8ae9a) }

var fileDescriptor_e25b6e050ad8ae9a = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x48, 0x2d, 0x2a,
	0xce, 0xcf, 0xd3, 0x87, 0x50, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x7c, 0xa9, 0x15, 0x89,
	0xb9, 0x05, 0x39, 0xa9, 0x7a, 0x10, 0x51, 0x29, 0xde, 0xd4, 0xca, 0x54, 0xfd, 0xd4, 0xca, 0x54,
	0x88, 0xb4, 0xd2, 0x14, 0x46, 0x2e, 0xde, 0x00, 0xb0, 0x8c, 0x6f, 0x6a, 0x71, 0x71, 0x62, 0x7a,
	0xaa, 0x90, 0x00, 0x17, 0x73, 0x62, 0x7a, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x88,
	0x29, 0x24, 0xcb, 0xc5, 0x95, 0x96, 0x59, 0x54, 0x5c, 0x12, 0x9f, 0x97, 0x98, 0x9b, 0x2a, 0xc1,
	0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0xc4, 0x09, 0x16, 0xf1, 0x4b, 0xcc, 0x4d, 0x15, 0x92, 0xe6, 0xe2,
	0xcc, 0x49, 0x84, 0xc9, 0x32, 0x83, 0x65, 0x39, 0x40, 0x02, 0x60, 0x49, 0x53, 0x2e, 0xae, 0xd4,
	0xca, 0xd4, 0xf8, 0xe4, 0xfc, 0x9c, 0xfc, 0xd2, 0x22, 0x09, 0x16, 0x05, 0x46, 0x0d, 0x3e, 0x23,
	0x31, 0x3d, 0x98, 0x9b, 0x40, 0xee, 0x70, 0xad, 0x4c, 0x75, 0x06, 0xcb, 0x06, 0x71, 0xa6, 0xc2,
	0x98, 0x4e, 0x5c, 0x51, 0x1c, 0x10, 0xf7, 0x16, 0x24, 0x25, 0xb1, 0x81, 0x5d, 0x6a, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x36, 0x3a, 0x10, 0x23, 0xdf, 0x00, 0x00, 0x00,
}
